version: "1.0.0"
services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8000:3000"
      - "443:3000"
      - "8080:3000"
    links:
      - backend

